config/routes.rb
Ezuser::Application.routes.draw do
  resources :contents, :only => [:create, :update]
  
  resources :pads, :except => [:edit] do
    collection do
      post 'append'
    end
  end

  resources :sessions, :only => [:new, :create] do
    collection do
      get 'logout'
    end
  end

  resources :users
  resources :tags, :only => [:index, :show] 

  root :to => "welcome#index"

end

app/models/pad.rb
class Pad < ActiveRecord::Base
  acts_as_taggable
  
  belongs_to :user
  belongs_to :category
  has_many :contents, :order => "contents.position asc"
  
  validates :title, 
    :presence   => true
    
end

app/controllers/pads_controller.rb
class PadsController < ApplicationController
  
  before_filter :login_required, :only => [:new, :create, :update]
  
  # GET /pads
  # GET /pads.xml
  def index
    @pads = Pad.paginate(
      :select   => "users.name as username, pads.*",
      :joins    => "left join users on users.id = pads.user_id", 
      :page     => params[:page], 
      :per_page => 20, 
      :order    => "pads.id desc")
    @page_title = "All Pads"

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pads }
    end
  end

  # GET /pads/1
  # GET /pads/1.xml
  def show
    @pad = Pad.find(params[:id])
    @contents = @pad.contents
    @tags = Tag.all

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pad }
    end
  end

  # GET /pads/new
  # GET /pads/new.xml
  def new
    @pad = Pad.new
    @tags = Tag.all
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /pads/1/edit
  def edit
    @pad = Pad.find(params[:id])
  end

  # POST /pads
  # POST /pads.xml
  def create
    @pad = Pad.new(params[:pad])
    @pad.user_id = session[:user_id]
    respond_to do |format|
      if @pad.save
        Content.create([
          {:pad_id => @pad.id, :body => params[:text_body], :used_for => "text", :position => 1, :user_id => session[:user_id], :content_type => params[:content_type]},
          {:pad_id => @pad.id, :body => params[:code_body], :used_for => "code", :position => 2, :user_id => session[:user_id], :code_language => params[:code_language]}
        ])
        flash[:notice] = "welcome to EZPad, continue edit, and injoy it !!!"
      else
        @msg = @pad.errors.full_messages.join(',')
      end
      format.js
    end
  end

  # PUT /pads/1
  # PUT /pads/1.xml
  def update
    @pad = Pad.find(params[:id])

    respond_to do |format|
      if @pad.update_attributes(params[:pad])
        format.html { redirect_to(@pad, :notice => 'Pad was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pad.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pads/1
  # DELETE /pads/1.xml
  def destroy
    @pad = Pad.find(params[:id])
    @pad.destroy

    respond_to do |format|
      format.html { redirect_to(pads_url) }
      format.xml  { head :ok }
    end
  end
  
  def append
    @content = Content.new(:position => 33)
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/pads_helper.rb
module PadsHelper
  def code_language_select_tag
    select_tag :code_language, options_for_select(SITE_SETTINGS["code_language"], "ruby"), :include_blank => true
  end
  
  def content_type_select_tag
    select_tag :content_type, options_for_select(SITE_SETTINGS["content_type"], "code collector"), :include_blank => true
  end
  
  def ej(str)
    escape_javascript( str )
  end
  
  def highlight_code(content, syntax)
    str = Uv.parse(content, "xhtml", syntax, true, "cobalt")
    str.gsub!(/(\n)/, "<br />")
    raw str
  rescue
    content_tag(:div, "code highlight error, please check your code language is right ???", :id => "error_div")
  end
  
  def warp_code(content)
    content_tag(:div, highlight_code(content.body, content.code_language), :class => "code_plain clearfix", :id => "items-#{content.id}")
  end
  
end

app/views/pads/_code_editor.html.haml
%div{:class => "code", :id => "content_#{content.id}_div"}
  = form_for content, :remote => true, :html => {:id => "content_#{content.id}_form"} do |f|
    = f.hidden_field :position
    %h3.grey
      .small.right.normal-font
        Code Language is
        = code_language_select_tag
      Code
    %div= f.text_area :body, :cols => 60, :rows => 5, :class => "code"

app/views/pads/_code_plain.html.haml
%div{:class => "code", :id => "content_#{content.id}_div"}
  = warp_code(content)

app/views/pads/_code_sample.html.haml
%div
  %h3.grey
    .small.right.normal-font
      Code Language is
      = code_language_select_tag
    Code
  %div= text_area_tag :code_body, '# it\'s a ruby code sample.', :cols => 60, :rows => 5, :class => "code"

app/views/pads/_sider.html.haml
.sider
  %ul
    - for tag in @tags
      %li
        %small.right.grey= tag.taggings_count
        = link_to tag.name, tag_path(tag.name)

app/views/pads/_text_editor.html.haml
%div{:class => "text", :id => "content_#{content.id}_div"}
  = form_for content, :remote => true, :html => {:id => "new_content_#{content.id}_form"} do |f|
    = f.hidden_field :position
    %h3.grey 
      .small.right.normal-font
        Content Type is
        = content_type_select_tag
        = nbsp(2)
        = link_to "del", js_void, :onclick => "slideup_and_remove('#content_#{content.id}_div')"
      Text
    %div
      = f.text_area :body, :name => "text_editor_#{content.id}"
      :javascript
        CKEDITOR.replace( "text_editor_#{content.id}" );

app/views/pads/_text_plain.html.haml
%div{:class => "text", :id => "content_#{content.id}_div"}
  = raw content.body

app/views/pads/_text_sample.html.haml
%div
  %h3.grey 
    .small.right.normal-font
      Content Type is
      = content_type_select_tag
    Text
  %div
    = text_area_tag :text_body, "it's a text sample <br /> you can input your content, or press 'OK', we will shou you more functions. funny."
    :javascript
      CKEDITOR.replace( "text_body" );

app/views/pads/index.html.haml
%table.list-table
  %tr
    %th{:width=>"60%"} Title
    %th Name
  - @pads.each do |pad|
    %tr
      %td
        = link_to pad.title, pad
      %td
        = link_to pad.username, user_path(pad.user_id)

%br
= will_paginate @pads, :previous_label => "&lt;&lt;", :next_label => "&gt;&gt;", :class => "flickr_pagination"
	  

app/views/pads/new.html.haml
- content_for :header do
  = javascript_include_tag :ckeditor
.pad
  .new
    = form_for @pad, :remote => true do |f|
      %h3 New Pad Title
      = f.text_field :title, :size => 80
      = render :partial => "text_sample"
      = render :partial => "code_sample"
      .text-center
        = submit_tag("  OK  ")

  = render :partial => "sider"
  .clearfix

app/views/pads/show.html.haml
.pad
  .show
    %h2= @pad.title
    - for content in @contents
      = render :partial => "#{content.used_for}_plain", :locals => {:content => content}
  = render :partial => "sider"
  .clearfix