config/routes.rb
Ezuser::Application.routes.draw do
  resources :contents, :only => [:create, :update]
  
  resources :pads, :except => [:edit] do
    collection do
      post 'append'
    end
  end

  resources :sessions, :only => [:new, :create] do
    collection do
      get 'logout'
    end
  end

  resources :users
  resources :tags, :only => [:index, :show] 

  root :to => "welcome#index"

end

app/views/layouts/application.html.haml
!!!
%html(xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en")
  %head
    %title= seo_title
    %meta{'http-equiv' => "content-type", :content => "text/html; charset=UTF-8"}
    %meta{'name' => "keywords", :content => "#{SITE_SETTINGS["keywords"]}"}
    %meta{'name' => "description", :content => "#{SITE_SETTINGS["description"]}"}
    %meta{'name' => "author", :content => "#{SITE_SETTINGS["author"]}"}
    = stylesheet_link_tag "style", "jquery.jgrowl", "pagination", "syntax/cobalt"
    = javascript_include_tag :defaults, "jquery.jgrowl"
    = csrf_meta_tag
    = yield :header
  %body
    .wrap
      .nav
        %ul
          %li{:class => "logo"}= link_to "EZPad", root_path
          %li{:class => "select"}= link_to "Pads", pads_path
          - if logined?
            %li= link_to "My Profile", user_path(session[:user_id])
            %li= link_to "Logout", logout_sessions_path
            %li{:class => "button"}= link_to "new pad", new_pad_path
          - else
            %li= link_to "Login", new_session_path
            %li= link_to "Signup", new_user_path
          .clearfix
  
      .notice_and_error_div
        - if flash[:notice]
          .green#notice_div
            = flash[:notice]
        - if flash[:error]
          .red#error_div= flash[:error]
    
      = yield
      .footer
        &copy; 2010 EZPad, code collector for you.